googleClientId: 37775297136-krc6ss8ema49fb5pakb80upi1d69t7kv.apps.googleusercontent.com
googleSecretKey: EokHyRvEOQlblYSJJqZqU12a

googleClientId :: Text
googleClientId = "37775297136-krc6ss8ema49fb5pakb80upi1d69t7kv.apps.googleusercontent.com"

googleSecretKey :: Text
googleSecretKey = "EokHyRvEOQlblYSJJqZqU12a"
